/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return service health status and available backends.
         *
         *     Returns:
         *         Dict with status and list of available backends.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Serve the chat UI.
         *
         *     Args:
         *         request: Incoming FastAPI request.
         *
         *     Returns:
         *         Rendered index.html template.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Run the RAG pipeline non-blocking and return an answer.
         *
         *     Runs the pipeline in a thread pool so the event loop is free to handle
         *     other requests while waiting for LLM responses.
         *
         *     Args:
         *         query: Validated request with question, max_contexts, and backend.
         *                backend is 'local' (Phi-3), 'anthropic' (Haiku), or 'agent'.
         *
         *     Returns:
         *         QueryResponse with answer, retrieved contexts, config name, and latency.
         */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Profile
         * @description Store a player profile as semantic memory facts.
         *
         *     Converts structured profile fields into natural language facts and upserts
         *     them into the vector memory store so they are retrieved on every question.
         *
         *     Args:
         *         profile: Validated player profile from the onboarding form.
         *
         *     Returns:
         *         Dict with status and number of facts stored.
         */
        post: operations["save_profile_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /**
             * Max Contexts
             * @default 5
             */
            max_contexts: number;
            /**
             * Backend
             * @default local
             */
            backend: string;
            /** Session Id */
            session_id?: string;
        };
        /**
         * QueryResponse
         * @description HTTP response shape — trimmed subset of PipelineResult.
         */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Contexts */
            contexts: components["schemas"]["RetrievedContext"][];
            /** Config Name */
            config_name: string;
            /** Total Time Ms */
            total_time_ms: number;
        };
        /** RetrievedContext */
        RetrievedContext: {
            /** Chunk Id */
            chunk_id: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /**
         * UserProfile
         * @description Player profile submitted from the onboarding form.
         */
        UserProfile: {
            /** Session Id */
            session_id: string;
            /** Position */
            position: string;
            /** Level */
            level: string;
            /** Sessions Per Week */
            sessions_per_week: number;
            /** Playing Since */
            playing_since: string;
            /** Age */
            age: number;
            /**
             * Goal
             * @default
             */
            goal: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
